version: "3.9"
services:
  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    command: python app.py
    container_name: backend
    networks:
      - shared_network      
    restart: always

  nginx-proxy:
    build:
      context: nginx/.
      dockerfile: Dockerfile
    container_name: nginx-proxy
    volumes:
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - BACKEND_SERVICE=backend
      - FRONTEND_SERVICE=frontend
    networks:
      - shared_network
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
    networks:
        - shared_network
    restart: unless-stopped

networks:
  shared_network:
    external: false
