version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../../:/workspace:cached

    # Keeps the container running
    command: sleep infinity

    # Allows "forwardPorts" in devcontainer.json to forward app ports locally.
    network_mode: bridge

volumes:
  app-data:
